name: ci

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - 'azure_func_git/src/FuncTest1/**'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use (6.0.401)
  WORKING_DIRECTORY: ./azure_func_git/src/dotnet/FuncTest1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install Dependencies
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # - name: Checkout code #
      #   run: actions/checkout@v3
      #   working-directory: ${{ env.WORKING_DIRECTORY }}
      
      # Install Azure Functions Tools
      # - name: Install Azure Functions Tools
      #   run: |
      #     dotnet tool install --global Microsoft.Azure.Functions.Tools

      # - name: Restore dependencies #
      #   run: dotnet restore
      #   working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run Test
        run: dotnet test --no-restore --verbosity normal --filter Category=Unit
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear